"""empty message

Revision ID: fd16c4abf3b3
Revises: 
Create Date: 2021-04-19 15:01:21.336271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd16c4abf3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distance_bar', 'patient_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('distance_bar', 'patient_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
